local util = require "__core__/lualib/util"
local shared = require "__PowerOverload__/shared"
require "__PowerOverload__/prototypes/huge-pole"
require "__PowerOverload__/prototypes/power-interface"
require "__PowerOverload__/prototypes/fuses"
require "__PowerOverload__/prototypes/fuse-remnants"
require "__PowerOverload__/prototypes/fuse-graphics"
require "__PowerOverload__/prototypes/fuse-recipes"  -- Mostly overriden in data-updates
require "__PowerOverload__/prototypes/transformer"
require "__PowerOverload__/prototypes/technology"
require "__PowerOverload__/prototypes/shortcuts"
require "__PowerOverload__/prototypes/tips-and-tricks"
